#include "scan_insert.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <limits.h>

ScanEngine* scan_create(Circuit* circuit) {
    if (!circuit) return NULL;
    
    ScanEngine* engine = (ScanEngine*)malloc(sizeof(ScanEngine));
    if (!engine) return NULL;
    
    engine->circuit = circuit;
    engine->scan_circuit = NULL;
    engine->chains = NULL;
    engine->num_chains = 0;
    engine->dff_list = NULL;
    engine->num_dffs = 0;
    engine->scan_enable_added = false;
    strcpy(engine->scan_enable, "scan_enable");
    
    return engine;
}

void scan_free(ScanEngine* engine) {
    if (!engine) return;
    
    if (engine->chains) {
        for (int i = 0; i < engine->num_chains; i++) {
            if (engine->chains[i].dff_ids) {
                free(engine->chains[i].dff_ids);
            }
        }
        free(engine->chains);
    }
    
    if (engine->dff_list) {
        free(engine->dff_list);
    }
    
    // Don't free scan_circuit or circuit - caller manages them
    
    free(engine);
}

int scan_find_dffs(ScanEngine* engine) {
    if (!engine || !engine->circuit) return 0;
    
    Circuit* circuit = engine->circuit;
    
    // Count DFFs
    int dff_count = 0;
    for (int i = 0; i < circuit->num_gates; i++) {
        if (circuit->gates[i].type == GATE_DFF) {
            dff_count++;
        }
    }
    
    if (dff_count == 0) {
        printf("Warning: No DFFs found in circuit\n");
        return 0;
    }
    
    // Allocate DFF list
    engine->dff_list = (int*)malloc(dff_count * sizeof(int));
    engine->num_dffs = 0;
    
    // Collect DFF IDs
    for (int i = 0; i < circuit->num_gates; i++) {
        if (circuit->gates[i].type == GATE_DFF) {
            engine->dff_list[engine->num_dffs++] = i;
        }
    }
    
    printf("Found %d DFFs in circuit\n", engine->num_dffs);
    return engine->num_dffs;
}

bool scan_insert_chains(ScanEngine* engine, int num_chains) {
    if (!engine || num_chains <= 0 || num_chains > MAX_CHAINS) {
        return false;
    }
    
    if (engine->num_dffs == 0) {
        printf("Error: No DFFs found. Run scan_find_dffs first.\n");
        return false;
    }
    
    printf("\nInserting %d scan chain(s) for %d DFFs...\n", num_chains, engine->num_dffs);
    
    // Allocate chains
    engine->chains = (ScanChain*)calloc(num_chains, sizeof(ScanChain));
    engine->num_chains = num_chains;
    
    // Distribute DFFs among chains
    int base_length = engine->num_dffs / num_chains;
    int remainder = engine->num_dffs % num_chains;
    
    int dff_idx = 0;
    for (int chain_id = 0; chain_id < num_chains; chain_id++) {
        ScanChain* chain = &engine->chains[chain_id];
        
        chain->chain_id = chain_id;
        snprintf(chain->si_port, MAX_NAME_LEN, "scan_in_%d", chain_id);
        snprintf(chain->so_port, MAX_NAME_LEN, "scan_out_%d", chain_id);
        
        // Calculate chain length
        int chain_length = base_length + (chain_id < remainder ? 1 : 0);
        
        chain->capacity = chain_length;
        chain->dff_ids = (int*)malloc(chain_length * sizeof(int));
        chain->num_dffs = chain_length;
        
        // Assign DFFs to this chain
        for (int i = 0; i < chain_length && dff_idx < engine->num_dffs; i++) {
            chain->dff_ids[i] = engine->dff_list[dff_idx++];
        }
    }
    
    printf("Scan chain insertion complete\n");
    return true;
}

bool scan_save_scandef(const ScanEngine* engine, const char* filename) {
    if (!engine || !filename) return false;
    
    FILE* file = fopen(filename, "w");
    if (!file) {
        fprintf(stderr, "Error: Cannot write to file %s\n", filename);
        return false;
    }
    
    fprintf(file, "# Scan Chain Definition File\n");
    fprintf(file, "# Generated by scan_insert (C implementation)\n\n");
    fprintf(file, "DESIGN %s\n", "circuit");
    fprintf(file, "NUM_CHAINS %d\n", engine->num_chains);
    fprintf(file, "TOTAL_SCAN_CELLS %d\n\n", engine->num_dffs);
    
    for (int i = 0; i < engine->num_chains; i++) {
        const ScanChain* chain = &engine->chains[i];
        fprintf(file, "CHAIN %d\n", chain->chain_id);
        fprintf(file, "  SI %s\n", chain->si_port);
        fprintf(file, "  SO %s\n", chain->so_port);
        fprintf(file, "  LENGTH %d\n", chain->num_dffs);
        fprintf(file, "  CELLS\n");
        
        for (int j = 0; j < chain->num_dffs; j++) {
            Gate* gate = circuit_get_gate(engine->circuit, chain->dff_ids[j]);
            if (gate) {
                fprintf(file, "    %s\n", gate->name);
            }
        }
        fprintf(file, "\n");
    }
    
    fclose(file);
    printf("Scan definition saved to %s\n", filename);
    return true;
}

void scan_print_stats(const ScanEngine* engine) {
    if (!engine) return;
    
    printf("\n============================================================\n");
    printf("SCAN CHAIN INSERTION REPORT\n");
    printf("============================================================\n");
    printf("Total chains: %d\n", engine->num_chains);
    printf("Total scan cells: %d\n", engine->num_dffs);
    
    if (engine->num_chains > 0) {
        int max_len = 0, min_len = INT_MAX;
        for (int i = 0; i < engine->num_chains; i++) {
            if (engine->chains[i].num_dffs > max_len) {
                max_len = engine->chains[i].num_dffs;
            }
            if (engine->chains[i].num_dffs < min_len) {
                min_len = engine->chains[i].num_dffs;
            }
        }
        
        printf("Max chain length: %d\n", max_len);
        printf("Min chain length: %d\n", min_len);
        printf("Shift cycles reduced: %d -> %d (%.1f%% reduction)\n\n",
               engine->num_dffs, max_len,
               100.0 * (engine->num_dffs - max_len) / engine->num_dffs);
        
        printf("Chain details:\n");
        for (int i = 0; i < engine->num_chains; i++) {
            const ScanChain* chain = &engine->chains[i];
            printf("  Chain %d: %d cells\n", chain->chain_id, chain->num_dffs);
            printf("    SI: %s, SO: %s\n", chain->si_port, chain->so_port);
        }
    }
    printf("============================================================\n\n");
}
